export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: { sans: ['Inter', 'sans-serif'] },
      colors: {
        "primary": "#742fe5",
        "primary-dim": "#681ad9",
        "primary-fixed": "#8342f4",
        "primary-fixed-dim": "#7632e7",
        "primary-container": "#8342f4",
        "inverse-primary": "#a476ff",
        "secondary": "#635b71",
        "secondary-dim": "#575065",
        "secondary-container": "#e9def8",
        "secondary-fixed": "#e9def8",
        "secondary-fixed-dim": "#dbd0e9",
        "tertiary": "#7d516e",
        "tertiary-dim": "#6f4662",
        "tertiary-container": "#fbc4e6",
        "tertiary-fixed": "#fbc4e6",
        "tertiary-fixed-dim": "#ecb7d8",
        "background": "#f8f9fa",
        "surface": "#f8f9fa",
        "surface-dim": "#d5dbdd",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f5",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#dee3e6",
        "surface-variant": "#dee3e6",
        "surface-tint": "#742fe5",
        "on-surface": "#2d3335",
        "on-surface-variant": "#5a6062",
        "on-background": "#2d3335",
        "on-primary": "#fdf7ff",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#e5d5ff",
        "on-secondary": "#fdf7ff",
        "on-secondary-container": "#564e63",
        "on-secondary-fixed": "#433c50",
        "on-secondary-fixed-variant": "#60586d",
        "on-tertiary": "#fff7f9",
        "on-tertiary-container": "#643c58",
        "on-tertiary-fixed": "#4f2944",
        "on-tertiary-fixed-variant": "#6f4561",
        "outline": "#767c7e",
        "outline-variant": "#adb3b5",
        "inverse-surface": "#0c0f10",
        "inverse-on-surface": "#9b9d9e",
        "error": "#a8364b",
        "error-dim": "#6b0221",
        "error-container": "#f97386",
        "on-error": "#fff7f7",
        "on-error-container": "#6e0523",
        "brand": {
          50:  "#f5f3ff",
          100: "#ede9fe",
          200: "#ddd6fe",
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
          700: "#6d28d9",
          800: "#5b21b6",
        }
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      boxShadow: {
        soft: "0 2px 15px -3px rgba(0,0,0,0.07), 0 10px 20px -2px rgba(0,0,0,0.04)",
        card: "0 1px 3px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.03)",
      }
    },
  },
  plugins: [],
}